name: anishportfoilio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  font_awesome_flutter: ^10.7.0
  get: ^4.2.2
  url_launcher: ^6.0.20
  firebase_database: ^11.0.4
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  firebase_storage: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/gif/


